#!/usr/bin/env php
<?php
/**
 * pre commit hook to copy in the ./git/hooks folder
 *
 * ! don't forget it to make it executable
 *
 * using a Docker running PHP container,
 * - asks if the user has updated the `composer.json.prod` file ?
 * - lints PHP code in
 *  - src
 *  - tests
 * - checks if PHPUnit tests pass
 */

// reminding the developer to update the `composer.json.prod` file
echo 'Dont forget to update the `composer.json.prod` file...' . PHP_EOL;

// linting
echo PHP_EOL.'linting PHP Code...'.PHP_EOL;
exec('./vendor/bin/php-cs-fixer fix src');
exec('./vendor/bin/php-cs-fixer fix tests');

// run tests
echo PHP_EOL.'Running PHPUnit tests...'.PHP_EOL;
exec(
    'docker exec -t wwwyactouatcom-fr-app-1 bash -c "XDEBUG_MODE=off /var/www/html/vendor/bin/phpunit --testdox --colors /var/www/html/tests"',
    $unitTestsOutput,
    $unitTestReturnCode
);
echo PHP_EOL . implode(PHP_EOL, $unitTestsOutput) . PHP_EOL;
if ($unitTestReturnCode !== 0) {
    echo 'Aborting commit because tests did not pass...' . PHP_EOL;
    exit(1);
}

// adding linting changes
exec('git add .');

exit(0);
